//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPSolution.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDB
    {
        public int IdEmplyee { get; set; }
        public int idCompany { get; set; }
        public string experience { get; set; }
        public System.DateTime startDate { get; set; }
        public int salary { get; set; }
        public int vacationDays { get; set; }
    
        public virtual CompaniesDB CompaniesDB { get; set; }
    }
}
